import { Cairo } from 'next/font/google'
import './globals.css'
import '@/components/Dashboard/style.css'
const inter = Cairo({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
